name: Docker Image Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    uses: ./.github/workflows/trivy-scan.yml@main
    with:
      image-ref: 'tanveermeman/php:latest'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
