name: Docker Image Scan

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------------------------------------------
      # Login to Docker Hub (required to pull the image)
      # ------------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ------------------------------------------------------------
      # Run Trivy vulnerability scanner 
      # ------------------------------------------------------------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tanveermeman/php:latest'
          format: 'table'
          exit-code: '1' 
          severity: 'CRITICAL' 

      # ------------------------------------------------------------
      # Logout of Docker Hub 
      # ------------------------------------------------------------
      - name: Echo before logout
        run: echo "About to logout..."

      - name: Logout of Docker Hub
        uses: docker/logout-action@v2
        continue-on-error: true # Continue even if logout fails

      - name: Echo after logout
        run: echo "Logout step completed (or skipped)."
