name: Trivy Scan Workflow

on:
  workflow_call:
    inputs:
      image-ref:
        description: 'Docker image reference to scan'
        required: true
        type: string
      format:
        description: 'Output format for Trivy'
        required: false
        default: 'table'
        type: string
      severity:
        description: 'Severity levels to report'
        required: false
        default: 'CRITICAL,HIGH'
        type: string

jobs:
  trivy-scan:
    runs-on: self-hosted
    steps:
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: ${{ inputs.format }}
          severity: ${{ inputs.severity }}
