name: Docker Image Scan

on:
  push:
    branches:
      - main  # Replace with your main branch name
  # Trigger on pull requests to main branch
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: tanveermeman/php:latest
          fail-build: true  # Fail the workflow if vulnerabilities are found

      - name: Logout of Docker Hub
        uses: docker/logout-action@v2
