name: Trivy Scan Reusable Workflow

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: 'table'
          severity: 'CRITICAL'

      - name: Logout of Docker Hub
        uses: docker/logout-action@v2
